name: Daily Future Pipeine

on:
  schedule:
    - cron: '17 * * * *'  # Runs at minute 0 of every hour
    # This targets 00, 01, 02, 03 UTC (which is 5, 6, 7, 8 AM Karachi)
    - cron: '12 0,1,2,3 * * *'
  workflow_dispatch:      # Allows you to click a button to run it manually

jobs:
  update-feature-store:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Feature Pipeline Script
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          AQI_API_KEY: ${{ secrets.AQI_API_KEY }}
        # GitHub starts in the root, so you must point to the folder
        run: python src/feature_pipeline.py
